Add dockerignore file
snyk/driftctl-action pull request #1
Opened 2021-03-26 11:11 UTC by KeisukeYamashita

## What

Add `.dockerignore` file.

## Why

Lighter images to make the CI faster and improve the network load.

2021-03-31 10:35 UTC, wbeuil requested changes
Hello @KeisukeYamashita, thanks for your contribution.

I just found out that for public repo `Secrets are not passed to workflows that are triggered by a pull request from a fork`, that's why the Action failed.

2021-03-31 10:35 UTC, wbeuil commented on .dockerignore
> +action.yml
You could easily add `.github`, `LICENCE` and `README.md` to this list since we don't need them too.

2021-03-31 10:37 UTC, KeisukeYamashita commented
@wbeuil Yeah, forked PRs can't access to secrets and it needs maintainers approval!

Thanks for your reply.

2021-04-14 21:14 UTC, wbeuil commented
We added the .gitignore in the latest version of the github-action. I will close this issue. Thanks for your contribution.

2021-04-14 21:14 UTC, closed without merging